# Generated by Django 3.0.4 on 2020-03-31 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcetag',
            name='problems',
        ),
        migrations.DeleteModel(
            name='SolutionTag',
        ),
        migrations.DeleteModel(
            name='SourceTag',
        ),
    ]
