# Generated by Django 3.0.5 on 2020-04-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20200331_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='hints',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='problem',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
