# Generated by Django 3.0.5 on 2020-04-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20200405_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='content',
            new_name='statement',
        ),
    ]
