# Generated by Django 3.0.5 on 2020-04-05 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0004_auto_20200405_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='claiming_user_set',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
