# Generated by Django 3.0.4 on 2020-04-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_auto_20200406_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solution_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='staff_comment',
            field=models.TextField(default=''),
        ),
    ]
