# Generated by Django 3.0.5 on 2020-05-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_solutionscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='claiming_user_set',
        ),
    ]
