# Generated by Django 3.0.5 on 2020-05-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_remove_problem_claiming_user_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='answer_checker',
            field=models.TextField(default=''),
        ),
    ]
