# Generated by Django 3.0.5 on 2020-04-06 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0005_problem_claiming_user_set'),
        ('tags', '0002_tag_user_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=100)),
                ('pretty_name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folder.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='folder.Folder')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='problem_set',
            field=models.ManyToManyField(through='folder.ProblemPlace', to='problems.Problem'),
        ),
        migrations.AddField(
            model_name='folder',
            name='tag_set',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
