# Generated by Django 3.0.4 on 2020-03-29 21:02

from django.db import migrations

def create_root_folder(apps, schema_editor):
    Folder = apps.get_model('folder', 'Folder')
    Folder.objects.create(folder_name='all', pretty_name='/')

class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_root_folder),
    ]

