# Generated by Django 3.0.4 on 2020-03-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20200331_1420'),
        ('folder', '0002_create_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='problem_set',
            field=models.ManyToManyField(to='problems.Problem'),
        ),
    ]
