# Generated by Django 3.0.5 on 2020-04-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0003_folder_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='show_solution',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='folder',
            name='show_stats',
            field=models.IntegerField(default=1),
        ),
    ]
