# Generated by Django 3.0.5 on 2020-04-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('folder', '0003_folder_problem_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='tag_set',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
