# Generated by Django 3.0.5 on 2020-05-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_create_base_tags'),
        ('folder', '0004_auto_20200407_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='indirect_tag_set',
            field=models.ManyToManyField(related_name='indirect_tag_set', to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='tag_set',
            field=models.ManyToManyField(related_name='tag_set', to='tags.Tag'),
        ),
    ]
