# Generated by Django 3.0.5 on 2020-05-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='answer_checker',
            field=models.TextField(default=''),
        ),
    ]
