# Generated by Django 3.0.4 on 2020-03-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0002_auto_20200331_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_id', models.IntegerField(default=0)),
                ('problems', models.ManyToManyField(to='problems.Problem')),
            ],
        ),
    ]
