# Generated by Django 3.0.4 on 2020-04-08 10:32

from django.db import migrations
from tags.views import tag_types

def create_base_tags(apps, schema_editor):
    Tag = apps.get_model('tags', 'Tag')
    for i in range(len(4)):
        Tag.objects.create(name=tag_types[i], type_id=i, attachable=False)

class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_tag_attachable'),
    ]

    operations = [
        migrations.RunPython(create_base_tags),
    ]
